export { default as Instagram } from "./Instagram"
export { default as Facebook } from "./Facebook"
export { default as Spotify } from "./Spotify"
export { default as Youtube } from "./Youtube"
export { default as Amazon } from "./Amazon"
export { default as SoundCloud } from "./SoundCloud"
