backend:
  name: github
  repo: lpoulter1/gatsby-netlify-cms

media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    preview_path: "news/{{year}}/{{month}}/{{slug}}"
    label: News
    folder: /collections/news
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { name: body, label: Body, widget: markdown }